apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.prefix }}-apply-job
  annotations:
    {{- range $k, $v := .Values.apply.phaseTwo.annotations }}
    {{ $k }} : {{ $v }}
    {{- end }}
spec:
  template:
    spec:
      serviceAccountName: {{ .Values.prefix }}-apply-sa
      containers:
      - name: terraform
        image: ghcr.io/popout-dev/terraform-kube-jobs:{{ .Values.terraform.tag }}
        env:
        - name: TF_SRC_DIR
          value: {{ .Values.terraform.sourceDir }}
        - name: TF_DEST_DIR
          value: {{ .Values.terraform.destDir }}
        - name: TF_ACTION
          value: APPLY
        - name: TF_INSTALL_VERSION
          value: {{ .Values.terraform.version }}
      {{- range $v := .Values.terraform.envs}}
        - name: {{ $v.name }}
          value: {{ $v.value }}
      {{- end }}
        volumeMounts:
        - name: terraform-files
          mountPath: {{ .Values.terraform.sourceDir }}
      {{- range $v := .Values.terraform.configs }}
        - name: {{ $v.name }}
          mountPath: {{ $v.mountPath }}
      {{- end }}
      {{- range $v := .Values.terraform.secrets }}
        - name: {{ $v.name }}
          mountPath: {{ $v.mountPath }}
      {{- end }}      
      volumes:
        - name: terraform-files
          configMap:
            name: {{ .Values.terraform.tfFileConfigMap }}
      {{- range $v := .Values.terraform.configs }}
        - name: {{ $v.name }}
          configMap:
            name: {{ $v.configMapName }}
      {{- end }}
      {{- range $v := .Values.terraform.secrets }}
        - name: {{ $v.name }}
          secret:
            secretName: {{ $v.secretName }}
      {{- end }}  
      restartPolicy: Never    
  backoffLimit: {{ .Values.job.backoffLimit}}