apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.prefix }}-destroy-sa
  annotations:
    {{- range $k, $v := .Values.destroy.phaseOne.annotations }}
    {{ $k }} : {{ $v }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.prefix }}-destroy-secrets-role
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $k, $v := .Values.destroy.phaseOne.annotations }}
    {{ $k }} : {{ $v }}
    {{- end }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.prefix }}-destroy-leases-role
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $k, $v := .Values.destroy.phaseOne.annotations }}
    {{ $k }} : {{ $v }}
    {{- end }}
rules:
- apiGroups: ["coordination.k8s.io"] # "" indicates the core API group
  resources: ["leases"]
  verbs: ["get", "watch", "list", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prefix }}-destroy-secrets-binding
  annotations:
    {{- range $k, $v := .Values.destroy.phaseOne.annotations }}
    {{ $k }} : {{ $v }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.prefix }}-destroy-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.prefix }}-destroy-secrets-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prefix }}-destroy-leases-binding
  annotations:
    {{- range $k, $v := .Values.destroy.phaseOne.annotations }}
    {{ $k }} : {{ $v }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.prefix }}-destroy-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.prefix }}-destroy-leases-role
  apiGroup: rbac.authorization.k8s.io