

name: Main
on:
  push:
    branches:
      - main
jobs:
  unit-test:
    uses: ./.github/workflows/unit.yaml

  docker-build-and-deploy:
    needs: unit-test
    uses: ./.github/workflows/docker.yaml

  helm-deploy:
    needs: unit-test
    uses: ./.github/workflows/helm.yaml