name: Unit Test
on:
  workflow_call: {}

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v1

    - name: asdf install
      uses: asdf-vm/actions/install@v1

    - name: cache go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: unit test
      run: go test ./...