name: Unit Test
on:
  workflow_call: {}

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v1

    - name: asdf install
      uses: asdf-vm/actions/install@v1
    
    - name: unit test
      run: go test ./...